port: 4251

password: "me"

production: false

authorize:
  loginKey: 65HQ7noooo
  transactionKey: 9Hm63nooo

modules:
  - functions
  - query
  - acc
  - socket
  - voting
  - fs
  - collections
  - mail

loadSet:
  - lastSync

fs:
  collection: 'files'

  domains:
    'var.best': /var/www/var.best
    'spiritual.casa': /var/www/ilunafriq
    'realtrips.fun': /var/www/realtrips
    'comercy.com': /var/www/comercy
    'localhost': /home/mk/www/best
    'ilunafriq.local': /home/mk/www/ilunafriq
    'frolaz.casa': /var/www/frolaz
    'var.best': /var/www/var.best
    'sverve.6d.lt': /var/www/sverve
    '8.var.best': /var/www/8
    
  allowed:
    - 'C:/8'
    - 'C:/Users/user/Desktop/pineal.cc'
    - 'C:/Users/user/Desktop'
    - 'C:/Users/user/Pictures'
  folder:
    item: 'item.json'

path:
  modules: './modules/'
  files: '../files/'
  tmp: '../tmp/'
  ffmpeg: "./bin/ffmpeg.exe"
  ffprobe: "C:/lib/ffmpeg/bin/ffprobe.exe"
  youtube: '../files/tube/'
  certificates: 'certificates/'


templates_path: './templates/'

devMode: true
currency: EUR
lang: en

key: mk

wait: false

email:
  admin: "Ilunafriq <support@ilunafriq.com>"
  sender: "Ilunafriq <hello@ilunafriq.com>"
  host: mail.ilunafriq.com
  user: hello@ilunafriq.com
  password: '10711612'
  port: 587
  regSubject: "Welcome to Ilunafriq!"
  reactiveSubject: "Activation"
  sidSubject: "Forgot password request"

www:
  path: '/home/mk/www'
  sites:
    -
      domain: ilunafriq.local
      folder: ilunafriq
    -
      domain: localhost
      folder: best
      auth:
        twitter:
          key: ngA7AL76wXU2DcNhLqRtDGZfS
          secret: QRYc8rzGPIhrkuofsdWRY9hSOsXCJEj26fjaE8jl9EToAmPVQw
          access_token: 1169847530298826752-G7nE63aD1acf4YyjzYZADhsoo1DsSS
          access_secret: pUO0dqUcu9aw0HDWO35CPN9GMow9JyyvGaoOm8P7ykrj9
    
    -
      domain: 'ego.bid'
      folder: best
      auth:
        twitter:
          key: ngA7AL76wXU2DcNhLqRtDGZfS
          secret: QRYc8rzGPIhrkuofsdWRY9hSOsXCJEj26fjaE8jl9EToAmPVQw
          access_token: 1169847530298826752-G7nE63aD1acf4YyjzYZADhsoo1DsSS
          access_secret: pUO0dqUcu9aw0HDWO35CPN9GMow9JyyvGaoOm8P7ykrj9

acc:
  captcha: false
  emailConfirm: true

mongodb:
  path: mongodb://127.0.0.1:27017/fractal
  url: mongodb://fractal:k1P@127.0.0.1:27017
  name: fractal
  journal: true
  collections: [acc, gallery, users, files, tree, neuro, comments, reviews, thumbs, orders, scores, chats, catalog, stories, sites]

collections:
  messages:
    watch:
      pipeline:
        -
          $match:
            operationType: "insert"
      on:
        insert: true

tingoa:
  path: '../tingodb'
  collections: [acc, users, catalog, files, tree, neuro, rates]

trusted_emails: [mntask@gmail.com]

social:
   -
      service: twitter
      id: naTOWzhV7YCzoxuI4XmFl2ZLx
      secret: ivVEgcamqovHDKth9YX3u1Fq0Y8xleEaPtfH
      extendUserProfile: true
   -
      service: 'facebook'
      id: '190457318117099'
      secret: 2a615352fc0a54baee7b8
   -
      service: 'google'
      id: 314225556856-sagu098bq3mcontent.com
      secret: Md2iSYbdvae5XdXdzYGnwnAys
