port: 4251

password: "me"

production: false

authorize:
  loginKey: 65HQ7noooo
  transactionKey: 9Hm63nooo

modules:
  - functions
  - query
  - acc
  - socket
  - voting
  - fs
  - collections
  - mail
  - paypal

loadSet:
  - lastSync

fs:
  collection: 'files'

  domains:
    'var.best': /var/www/var.best
    'spiritual.casa': /var/www/ilunafriq
    'realtrips.fun': /var/www/realtrips
    'comercy.com': /var/www/comercy
    'localhost': /home/mk/www/best
    'ilunafriq.local': /home/mk/www/ilunafriq
    'frolaz.casa': /var/www/frolaz
    'var.best': /var/www/var.best
    'sverve.6d.lt': /var/www/sverve
    '8.var.best': /var/www/8
    
  allowed:
    - 'C:/8'
    - 'C:/Users/user/Desktop/pineal.cc'
    - 'C:/Users/user/Desktop'
    - 'C:/Users/user/Pictures'
  folder:
    item: 'item.json'

path:
  modules: './modules/'
  files: '../files/'
  tmp: '../tmp/'
  ffmpeg: "./bin/ffmpeg.exe"
  ffprobe: "C:/lib/ffmpeg/bin/ffprobe.exe"
  youtube: '../files/tube/'
  certificates: 'certificates/'


templates_path: './templates/'

devMode: true
lang: en

key: mk

wait: false

email:
  admin: "MK <mk@6d.lt>"
  sender: "FractalOS <info@6d.lt>"
  host: mail.6d.lt
  user: info@6d.lt
  password: 'fdhrt'
  port: 587
  regSubject: "Welcome!"
  reactiveSubject: "Activation"
  sidSubject: "Forgot password request"

www:
  default: 'ego.bid'
  path: '/home/mk/www'
  sites:
    -
      domain: localhost
      folder: best
      
    -
      domain: ilunafriq.ego.bid
      folder: ilunafriq
      title: Ilunafriq
      paypal:
        client_id: 'AZLdLNV4Uya3uXQRrHkC45Ysc1MG427aEu5NVaje0XjWcXiufU9hP2SBmRDL0VSGQ2zPncUNznIKCwvQ'
        client_secret: 'EPrt2r2g0y5Qy8Lmpm3CKx9NS7CoUAYkUleIBTFq1LA9cOPBdEj1fuP3vpCPSr_5A96TfgzEzPVfHnLV'

    -
      domain: ego.bid
      folder: best

currency: USD

acc:
  captcha: false
  emailConfirm: true

mongodb:
  path: mongodb://127.0.0.1:27017/fractal
  url: 'mongodb://127.0.0.1:27017'
  name: fractal
  journal: true
  collections: [acc, gallery, users, files, tree, neuro, comments, reviews, thumbs, orders, scores, chats, catalog, stories, sites]

collections:
  acc: {}
  users: {}
  tree: {}
  files: {}
  sites: {}
  stories: {}
  comments: {}
  subscribers:
    watch:
      pipeline:
        -
          $match:
            operationType: "update"
      
      on:
        insert: true
  reviews: {}
  chats:
    watch:
      pipeline:
        -
          $match:
            operationType: "update"
      
      on:
        insert: true
  messages:
    watch:
      pipeline:
        -
          $match:
            operationType: "insert"
      on:
        insert: true

tingoa:
  path: '../tingodb'
  collections: [acc, users, catalog, files, tree, neuro, rates]

trusted_emails: [mntask@gmail.com]

paypal:
  configure:
    mode: 'sandbox'
    client_id: 'AZLdLNV4Uya3uXQRrHkC45Ysc1MG427aEu5NVaje0XjWcXiufU9hP2SBmRDL0VSGQ2zPncUNznIKCwvQ'
    client_secret: 'EPrt2r2g0y5Qy8Lmpm3CKx9NS7CoUAYkUleIBTFq1LA9cOPBdEj1fuP3vpCPSr_5A96TfgzEzPVfHnLV'

social:
   -
      service: twitter
      id: naTOWzhV7YCzoxuI4XmFl2ZLx
      secret: ivVEgcamqovHDKth9YX3u1Fq0Y8xleEaPtfH
      extendUserProfile: true
   -
      service: 'facebook'
      id: '190457318117099'
      secret: 2a615352fc0a54baee7b8
   -
      service: 'google'
      id: 314225556856-sagu098bq3mcontent.com
      secret: Md2iSYbdvae5XdXdzYGnwnAys
